### ISSUE TITLE
Install Instructions Missing Files

### ISSUE THREAD

**Issue by pcwizrd** [bitpay/wordpress-ecommerce-plugin#27]
- Extract the contents of the zip file.
- Copy the wpsc-merchants folder and paste it into your active WP eCommerce instance (ie `/var/www/html/wordpress/wp-content/plugins/wp-e-commerce`).

The zip file doesn't extract files to a wpsc-merchants folder. The gits doesn't appear to include it either.

**Comment by aleitner** [comment]
You must be downloading the source code which doesn't have the plugin already setup. You need to download the zip file from a release if you want to see the wpsc-merchants folder. 
Follow the instructions [Here](https://github.com/bitpay/wordpress-ecommerce-plugin/releases/tag/v2.0.3) using this [Download](https://github.com/bitpay/wordpress-ecommerce-plugin/releases/download/v2.0.3/bitpay.zip)
Either that in the source code you can run ./setup 'database_user' 'database_password' .
This will setup the wpsc-merchants file for you. This method on the other hand requires database access and composer to be installed on your system.

**Comment by pcwizrd** [comment]
Thank you, this resolved the issue. Yes I was downloading the source, I 
couldn't locate the release.

On 1/5/2015 10:11 AM, Alexander Leitner wrote:
>
> You must be downloading the source code which doesn't have the plugin 
> already setup. You need to download the zip file from a release if you 
> want to see the wpsc-merchants folder.
> Follow the instructions Here 
> <https://github.com/bitpay/wordpress-ecommerce-plugin/releases/tag/v2.0.3> 
> using this Download 
> <https://github.com/bitpay/wordpress-ecommerce-plugin/releases/download/v2.0.3/bitpay.zip>
> Either that in the source code you can run ./setup 'database_user' 
> 'database_password' .
> This will setup the wpsc-merchants file for you. This method on the 
> other hand requires database access and composer to be installed on 
> your system.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bitpay/wordpress-ecommerce-plugin/issues/27#issuecomment-68712198>.
>

-- 
Scott Pettie - PCWizrd

Providing fast & effective on site support for Business and Home users
Book your appointment -  https://www.timetrade.com/book/VMDB6

Small/Medium & Corporate Businesses Solutions
Indoor/Outdoor Digital Signage & Computer Solutions
http://www.pcwizrd.org
http://www.hfxsigns.ca
http://www.hfxhosting.com
Phone: 902-800-4700
Email: pcwizrd@gmail.com
BTC - 1NnfNQhFzXv6eJTjvNe44BxiWjvNyzNRa
