### ISSUE TITLE
setup script shouldn't need MySQL password or use sudo

### ISSUE THREAD

**Issue by nmarley** [bitpay/wordpress-ecommerce-plugin#28]
This setup script is really not secure - should not assume things like /tmp/wordpress-test is not being used by the user already or the name of the database "wordpress_test", etc.

**Comment by ionux** [comment]
@nmarley Good point and I agree.  Thanks for the report!  A developer will be assigned to fix.

**Comment by ionux** [comment]
Hi @nmarley, this should be resolved in the latest update to the source.  Feel free to reopen this issue or start a new one if you have any other problems.
