### ISSUE TITLE
Automatic Recurring Payments Integration?

### ISSUE THREAD

**Issue by five23** [bitpay/wordpress-ecommerce-plugin#30]
Any chance this could be added to the roadmap? See screenshot below -- not exactly sure what's involved, but willing to help if pointed in the right direction.

![bitpay](https://cloud.githubusercontent.com/assets/1984651/7121819/315088b6-e1e5-11e4-8890-f5d8047d14c3.gif)

**Comment by ionux** [comment]
It's not on the roadmap currently, but you can always submit a PR implementing the functionality!  My and my team certainly would welcome the help! :)

**Comment by five23** [comment]
Gotcha, forking now -- will see if I can get my time approved at work to add this feature.
