### ISSUE TITLE
Building BitPay Plugin

### ISSUE THREAD

**Issue by TheBudda** [bitpay/wordpress-ecommerce-plugin#33]
I run ./setup username password .... I get this error. When I cp -r wpsc-merchants/ /wp-content/plugins/wp-e-commerce It causes my website to down down. I have to remove wp-e-commerce for my website to be live again

Can you please help

Building BitPay Plugin Directory...
cp: cannot stat ‘vendor/bitpay/php-client/src/*’: No such file or directory
Setup finished

**Comment by TheBudda** [comment]
I run ./setup username password .... I get this error. When I cp -r wpsc-merchants/  /wp-content/plugins/wp-e-commerce It causes my website to down down. I have to remove wp-e-commerce for my website to be live again

Can you please help

Building BitPay Plugin Directory...
cp: cannot stat ‘vendor/bitpay/php-client/src/*’: No such file or directory
Setup finished

**Comment by kleetus** [comment]
what is the operating system that you are running this on?

**Comment by TheBudda** [comment]
Debian 8

**Comment by kleetus** [comment]
You may not have a vendor directory in the same directory as the setup script. The reason for this is that maybe you did not run:

$ curl -sS https://getcomposer.org/installer | php
$ php composer.phar install

this may require other packages from Debian such as php5-curl, php5-mcrypt
